#!/usr/bin/env python3
"""Render Mermaid call graphs of the entrypoints from the miniwdl AST.

docs/guide/workflow-graphs.md is generated by this script, never edited by hand;
tests/check.sh fails when it is stale. Each entrypoint becomes one `flowchart TD`
with a node per call, a subgraph per scatter / if section and per inlined
workflow (depth 1: workflows called directly by the entrypoint are inlined,
workflows they call are drawn as one node), solid edges where a call output
feeds a call input and dashed edges where it feeds a section's expression.
Declarations that join several call outputs (`select_first([...])`) are drawn as
one stadium node; every other declaration, the workflow inputs and outputs and
the `backend_configuration` call are collapsed away. Every Mermaid source is
kept under MAX_CHARS because Forgejo renders at most
MERMAID_MAX_SOURCE_CHARACTERS (5000 by default).

Usage:
  python3 scripts/wdl-graph.py --write                 # regenerate docs/guide/workflow-graphs.md
  python3 scripts/wdl-graph.py --check                 # exit 1 with a diff when the file is stale
  python3 scripts/wdl-graph.py --print ugc_wgw_upstream    # bare Mermaid for one entrypoint
  python3 scripts/wdl-graph.py                         # the Markdown on stdout

Dev-time only: needs miniwdl importable (activate .venv). Nothing on the HPC
runs it. See docs/DESIGN.md §15 and §18 (2026-09-11).
"""
from __future__ import annotations

import argparse
import difflib
import itertools
import os
import pathlib
import sys
from dataclasses import dataclass, field
from typing import Dict, Iterable, Iterator, List, Optional, Set, Tuple

try:
    import WDL
    from WDL import Expr, Tree
except ImportError:  # pragma: no cover
    sys.exit("scripts/wdl-graph.py needs miniwdl (dev-time only): activate .venv or pip install miniwdl")

REPO = pathlib.Path(__file__).resolve().parents[1]
ENTRYPOINTS = ["ugc_wgw_singleton", "ugc_wgw_upstream", "ugc_wgw_cohort_call", "ugc_wgw_downstream", "ugc_wgw_cohort_merge", "ugc_wgw_cohort_freq",
               "ugc_wgw_assembly"]
OUTPUT = REPO / "docs" / "guide" / "workflow-graphs.md"
DEFAULT_DEPTH = 1
DEPTH: Dict[str, int] = {}  # per-entrypoint override of DEFAULT_DEPTH
HIDE = frozenset({"backend_configuration"})  # call names never drawn
MAX_CHARS = 4500  # Forgejo: MERMAID_MAX_SOURCE_CHARACTERS = 5000
EXPR_CHARS = 40

Key = Tuple[int, str]  # (scope serial, workflow node id)


class SizeError(Exception):
    pass


@dataclass
class Node:
    key: Key
    kind: str  # task | workflow | hub
    label: str


@dataclass
class Section:
    key: Key
    kind: str  # scatter | if | sub
    title: str
    children: List[object] = field(default_factory=list)


@dataclass
class Graph:
    root: List[object] = field(default_factory=list)
    edges: Set[Tuple[Key, Key, str]] = field(default_factory=set)  # style: data | ctl
    inlined: List[Tuple[str, str]] = field(default_factory=list)  # (call name, repo-relative file)
    linked: List[Tuple[str, str]] = field(default_factory=list)  # workflow calls drawn as one node
    serial: Iterator[int] = field(default_factory=itertools.count)


# ---- AST helpers -------------------------------------------------------------

def expr_deps(expr: Optional[Expr.Base]) -> Iterator[str]:
    """Workflow node ids referenced by an expression (public-API twin of miniwdl's helper)."""
    if expr is None:
        return
    if isinstance(expr, Expr.Ident) and isinstance(expr.referee, Tree.WorkflowNode):
        if not isinstance(expr.referee, Tree.WorkflowSection):
            yield expr.referee.workflow_node_id
    for ch in expr.children:
        if isinstance(ch, Expr.Base):
            yield from expr_deps(ch)


def expr_text(expr: Expr.Base, doc: Tree.Document) -> str:
    """The expression as written in the source, whitespace collapsed, truncated."""
    pos = expr.pos
    lines = doc.source_lines
    try:
        if pos.line == pos.end_line:
            txt = lines[pos.line - 1][pos.column - 1:pos.end_column - 1]
        else:
            parts = [lines[pos.line - 1][pos.column - 1:]]
            parts += lines[pos.line:pos.end_line - 1]
            parts.append(lines[pos.end_line - 1][:pos.end_column - 1])
            txt = " ".join(parts)
    except IndexError:
        txt = str(expr)
    txt = " ".join(txt.split())
    if len(txt) > EXPR_CHARS:
        txt = txt[:EXPR_CHARS - 1].rstrip() + "…"
    return txt


def esc(s: str) -> str:
    """Escape a Mermaid quoted label."""
    return (s.replace("#", "#35;").replace('"', "#quot;").replace("<", "#lt;")
            .replace(">", "#gt;").replace("&", "#38;"))


def has_calls(body: Iterable[Tree.WorkflowNode]) -> bool:
    for elt in body:
        if isinstance(elt, Tree.Call):
            return True
        if isinstance(elt, Tree.WorkflowSection) and has_calls(elt.body):
            return True
    return False


def collect_docs(doc: Tree.Document, acc: Optional[Dict[str, Tree.Document]] = None) -> Dict[str, Tree.Document]:
    acc = {} if acc is None else acc
    acc[doc.pos.abspath] = doc
    for imp in doc.imports:
        if imp.doc is not None and imp.doc.pos.abspath not in acc:
            collect_docs(imp.doc, acc)
    return acc


def relpath(abspath: str) -> str:
    """Repo-relative path for files under the repo, unchanged otherwise."""
    try:
        return str(pathlib.Path(abspath).resolve().relative_to(REPO))
    except ValueError:
        return abspath


# ---- one workflow's dependency structure --------------------------------------

class Scope:
    """Index of one Workflow's nodes with the collapsing rules of the diagram."""

    def __init__(self, wf: Tree.Workflow, doc: Tree.Document, hide: frozenset, serial: int) -> None:
        self.wf = wf
        self.doc = doc
        self.n = serial
        self.byid: Dict[str, Tree.WorkflowNode] = {}
        self.order: List[str] = []
        self.parent_of: Dict[str, int] = {}
        self.inputs: Set[str] = set()
        self.outputs: Set[str] = set()
        self.hidden: Set[str] = {"call-" + name for name in hide}
        self.hubs: Dict[str, str] = {}  # hub decl id -> representative decl id
        self.hubnames: Dict[str, List[str]] = {}
        self.keymap: Dict[str, Key] = {}  # rendered node id -> IR key
        self.inlined: Dict[str, "Scope"] = {}  # inlined call id -> inner scope
        self.rev: Dict[str, Set[str]] = {}

        def visit(node: Tree.WorkflowNode, parent: int) -> None:
            nid = node.workflow_node_id
            self.byid[nid] = node
            self.order.append(nid)
            self.parent_of[nid] = parent
            if isinstance(node, Tree.WorkflowSection):
                for ch in node.body:
                    visit(ch, id(node))
                for g in node.gathers.values():
                    visit(g, parent)

        for inp in wf.inputs or []:
            visit(inp, 0)
            self.inputs.add(inp.workflow_node_id)
        for elt in wf.body:
            visit(elt, 0)
        for outp in wf.outputs or []:
            visit(outp, 0)
            self.outputs.add(outp.workflow_node_id)
        for nid, node in self.byid.items():
            for dep in node.workflow_node_dependencies:
                self.rev.setdefault(dep, set()).add(nid)
        self._find_hubs()

    def anchors(self, dep: str, seen: Optional[Set[str]] = None) -> Set[str]:
        """Calls (or hub decls) that a dependency ultimately comes from."""
        node = self.byid.get(dep)
        if node is None:
            return set()
        if isinstance(node, Tree.Gather):
            return self.anchors(node.final_referee.workflow_node_id, seen)
        if isinstance(node, Tree.Call):
            return set() if dep in self.hidden else {dep}
        if isinstance(node, Tree.Decl):
            if dep in self.inputs:
                return set()
            if dep in self.hubs:
                return {self.hubs[dep]}
            seen = set() if seen is None else seen
            if dep in seen:
                return set()
            seen.add(dep)
            out: Set[str] = set()
            for d in node.workflow_node_dependencies:
                out |= self.anchors(d, seen)
            return out
        return set()

    def _find_hubs(self) -> None:
        decls = [nid for nid in self.order
                 if isinstance(self.byid[nid], Tree.Decl) and nid not in self.inputs and nid not in self.outputs]
        for _ in range(2):  # to a fixpoint: later hubs can absorb earlier candidates
            hubs: Dict[str, str] = {}
            groups: Dict[Tuple[frozenset, int], str] = {}
            for nid in decls:
                node = self.byid[nid]
                anchors: Set[str] = set()
                for d in node.workflow_node_dependencies:
                    anchors |= self.anchors(d)
                if len(anchors) < 2:
                    continue
                gkey = (frozenset(anchors), self.parent_of[nid])
                rep = groups.setdefault(gkey, nid)
                hubs[nid] = rep
            self.hubs = hubs
        self.hubnames = {}
        for nid, rep in self.hubs.items():
            self.hubnames.setdefault(rep, []).append(self.byid[nid].name)

    def consumers(self, start: str) -> Set[str]:
        """Rendered nodes (calls, sections, hub reps) that read a declaration, through pass-through decls."""
        out: Set[str] = set()
        seen = {start}
        stack = [start]
        while stack:
            cur = stack.pop()
            for c in self.rev.get(cur, ()):
                if c in seen:
                    continue
                seen.add(c)
                node = self.byid[c]
                if isinstance(node, (Tree.Call, Tree.WorkflowSection)):
                    out.add(c)
                elif c in self.hubs:
                    out.add(self.hubs[c])
                elif isinstance(node, (Tree.Decl, Tree.Gather)) and c not in self.outputs:
                    stack.append(c)
        return out


# ---- build, wire, prune, number, render ---------------------------------------

def build(scope: Scope, body: Iterable[Tree.WorkflowNode], depth: int, graph: Graph, hide: frozenset,
          docs: Dict[str, Tree.Document]) -> List[object]:
    out: List[object] = []
    for node in body:
        nid = node.workflow_node_id
        if isinstance(node, Tree.Call):
            if node.name in hide:
                continue
            callee = node.callee
            if isinstance(callee, Tree.Workflow) and depth > 0 and has_calls(callee.body):
                inner = Scope(callee, docs[callee.pos.abspath], hide, next(graph.serial))
                sec = Section((scope.n, nid), "sub", f"{node.name} ({os.path.basename(callee.pos.abspath)})")
                sec.children = build(inner, callee.body, depth - 1, graph, hide, docs)
                wire(inner, graph)
                scope.keymap[nid] = sec.key
                scope.inlined[nid] = inner
                graph.inlined.append((node.name, relpath(callee.pos.abspath)))
                out.append(sec)
            else:
                kind = "workflow" if isinstance(callee, Tree.Workflow) else "task"
                n = Node((scope.n, nid), kind, node.name)
                scope.keymap[nid] = n.key
                if kind == "workflow" and callee is not None:
                    graph.linked.append((node.name, relpath(callee.pos.abspath)))
                out.append(n)
        elif isinstance(node, Tree.Scatter):
            sec = Section((scope.n, nid), "scatter", f"scatter {node.variable} in {expr_text(node.expr, scope.doc)}")
            sec.children = build(scope, node.body, depth, graph, hide, docs)
            scope.keymap[nid] = sec.key
            out.append(sec)
        elif isinstance(node, Tree.Conditional):
            sec = Section((scope.n, nid), "if", f"if {expr_text(node.expr, scope.doc)}")
            sec.children = build(scope, node.body, depth, graph, hide, docs)
            scope.keymap[nid] = sec.key
            out.append(sec)
        elif isinstance(node, Tree.Decl) and scope.hubs.get(nid) == nid:
            n = Node((scope.n, nid), "hub", ", ".join(scope.hubnames[nid]))
            scope.keymap[nid] = n.key
            out.append(n)
    return out


def wire(scope: Scope, graph: Graph) -> None:
    """Add the edges of one scope; inlined workflows get precise input edges."""
    for nid, key in scope.keymap.items():
        node = scope.byid[nid]
        if nid in scope.inlined:
            assert isinstance(node, Tree.Call)
            inner = scope.inlined[nid]
            input_deps: Set[str] = set()
            for name, expr in node.inputs.items():
                deps = set(expr_deps(expr))
                input_deps |= deps
                sources: Set[str] = set()
                for d in deps:
                    sources |= scope.anchors(d)
                for src in sources:
                    if src not in scope.keymap:
                        continue
                    for c in inner.consumers("decl-" + name):
                        if c in inner.keymap:
                            style = "ctl" if isinstance(inner.byid[c], Tree.WorkflowSection) else "data"
                            graph.edges.add((scope.keymap[src], inner.keymap[c], style))
            for d in node.workflow_node_dependencies - input_deps:  # `after` clauses
                for src in scope.anchors(d):
                    if src in scope.keymap and src != nid:
                        graph.edges.add((scope.keymap[src], key, "data"))
            continue
        style = "ctl" if isinstance(node, Tree.WorkflowSection) else "data"
        for d in node.workflow_node_dependencies:
            for src in scope.anchors(d):
                if src in scope.keymap and src != nid:
                    graph.edges.add((scope.keymap[src], key, style))


def prune(root: List[object], edges: Set[Tuple[Key, Key, str]]) -> Tuple[List[object], Set[Tuple[Key, Key, str]]]:
    """Drop empty sections and hubs without both a source and a consumer, until stable."""
    while True:
        def keep(items: List[object]) -> List[object]:
            out: List[object] = []
            for it in items:
                if isinstance(it, Section):
                    it.children = keep(it.children)
                    if it.children:
                        out.append(it)
                elif isinstance(it, Node) and it.kind == "hub":
                    if any(e[0] == it.key for e in edges) and any(e[1] == it.key for e in edges):
                        out.append(it)
                else:
                    out.append(it)
            return out

        root = keep(root)
        keys: Set[Key] = set()

        def collect(items: List[object]) -> None:
            for it in items:
                keys.add(it.key)  # type: ignore[attr-defined]
                if isinstance(it, Section):
                    collect(it.children)

        collect(root)
        kept = {e for e in edges if e[0] in keys and e[1] in keys}
        if kept == edges:
            return root, edges
        edges = kept


def number(root: List[object]) -> Dict[Key, str]:
    ids: Dict[Key, str] = {}
    counters = {"n": itertools.count(1), "s": itertools.count(1)}

    def walk(items: List[object]) -> None:
        for it in items:
            if isinstance(it, Section):
                ids[it.key] = f"s{next(counters['s'])}"
                walk(it.children)
            else:
                ids[it.key] = f"n{next(counters['n'])}"

    walk(root)
    return ids


def render(root: List[object], edges: Set[Tuple[Key, Key, str]], ids: Dict[Key, str]) -> str:
    lines = ["flowchart TD"]

    def walk(items: List[object], indent: str) -> None:
        for it in items:
            if isinstance(it, Section):
                lines.append(f'{indent}subgraph {ids[it.key]}["{esc(it.title)}"]')
                walk(it.children, indent + "  ")
                lines.append(f"{indent}end")
            else:
                assert isinstance(it, Node)
                label = esc(it.label)
                if it.kind == "workflow":
                    lines.append(f'{indent}{ids[it.key]}[["{label}"]]')
                elif it.kind == "hub":
                    lines.append(f'{indent}{ids[it.key]}(["{label}"])')
                else:
                    lines.append(f'{indent}{ids[it.key]}["{label}"]')

    walk(root, "  ")

    def order(mid: str) -> Tuple[int, int]:
        return (0 if mid[0] == "n" else 1, int(mid[1:]))

    for src, dst, style in sorted(edges, key=lambda e: (order(ids[e[0]]), order(ids[e[1]]), e[2])):
        arrow = "-.->" if style == "ctl" else "-->"
        lines.append(f"  {ids[src]} {arrow} {ids[dst]}")
    return "\n".join(lines) + "\n"


def graph_for(path: pathlib.Path, depth: int = DEFAULT_DEPTH, hide: frozenset = HIDE,
              max_chars: int = MAX_CHARS) -> Tuple[str, Graph]:
    """Mermaid source and the Graph for one workflow file."""
    doc = WDL.load(str(path))
    if doc.workflow is None:
        raise SystemExit(f"{path}: no workflow")
    docs = collect_docs(doc)
    graph = Graph()
    scope = Scope(doc.workflow, doc, hide, next(graph.serial))
    graph.root = build(scope, doc.workflow.body, depth, graph, hide, docs)
    wire(scope, graph)
    graph.root, graph.edges = prune(graph.root, graph.edges)
    ids = number(graph.root)
    text = render(graph.root, graph.edges, ids)
    if len(text) > max_chars:
        raise SizeError(f"{path.name}: mermaid source is {len(text)} chars > {max_chars} "
                        "(Forgejo renders at most MERMAID_MAX_SOURCE_CHARACTERS=5000); "
                        f"lower DEPTH[{path.stem!r}] in scripts/wdl-graph.py or add boilerplate calls to HIDE")
    return text, graph


def markdown(depth: Optional[int] = None, hide: frozenset = HIDE, max_chars: int = MAX_CHARS) -> str:
    built: List[Tuple[str, int, str, Graph]] = []
    for ep in ENTRYPOINTS:
        d = depth if depth is not None else DEPTH.get(ep, DEFAULT_DEPTH)
        text, graph = graph_for(REPO / "workflows" / f"{ep}.wdl", d, hide, max_chars)
        built.append((ep, d, text, graph))
    inlined_in: Dict[str, List[str]] = {}
    for ep, _, _, graph in built:
        for _, rel in graph.inlined:
            inlined_in.setdefault(rel, []).append(ep)
    out = [
        "<!-- Generated by scripts/wdl-graph.py from workflows/ugc_wgw_*.wdl; do not edit.",
        "     Regenerate: python3 scripts/wdl-graph.py --write (tests/check.sh fails on drift). -->",
        "",
        "# Workflow call graphs",
        "",
        "Exact call graphs of the seven entrypoints, rendered from the miniwdl AST by",
        "`scripts/wdl-graph.py`. A workflow called directly by an entrypoint is inlined",
        "as a box; a workflow it calls in turn is one node. Simplified diagrams with",
        "the switches and resources explained are in `08-stages.md`.",
        "",
        "Legend:",
        "",
        "- `[\"name\"]` is a task call. The name is the call name, which is also the",
        "  `call-<name>` directory under the run's miniwdl work directory.",
        "- `[[\"name\"]]` is a call of a workflow that is not expanded in this diagram.",
        "- `([\"a, b\"])` is a declaration that joins several call outputs, for example",
        "  `select_first` over an optional merge and a single input.",
        "- Boxes are scatter sections (`scatter x in expr`), conditional sections",
        "  (`if expr`) and inlined workflows (`call name (file.wdl)`).",
        "- A solid arrow means an output of the source feeds an input of the target.",
        "  A dashed arrow means the source feeds the expression that controls a box.",
        "- Workflow inputs and outputs, plain declarations and the",
        f"  `{', '.join(sorted(hide))}` call are not drawn.",
        "",
    ]
    for ep, d, text, graph in built:
        out += [f"## {ep}", ""]
        out.append(f"Source `workflows/{ep}.wdl`, depth {d}, Mermaid source {len(text)} characters.")
        out.append("")
        if graph.inlined:
            out.append("Inlined workflows:")
            out.append("")
            out += [f"- `{name}`: `{rel}`" for name, rel in graph.inlined]
        else:
            out.append("Inlined workflows: none.")
        out.append("")
        if graph.linked:
            out.append("Workflow nodes (not expanded here):")
            out.append("")
            for name, rel in graph.linked:
                where = inlined_in.get(rel)
                note = "; inlined under " + ", ".join(f"`{w}`" for w in where) if where else ""
                out.append(f"- `{name}`: `{rel}`{note}")
        else:
            out.append("Workflow nodes (not expanded here): none.")
        out += ["", "```mermaid", text.rstrip("\n"), "```", ""]
    return "\n".join(out)


def check(text: str, target: pathlib.Path) -> int:
    rel = relpath(str(target))
    try:
        current = target.read_text()
    except FileNotFoundError:
        print(f"{rel}: missing", file=sys.stderr)
        return 1
    if current == text:
        return 0
    sys.stdout.writelines(difflib.unified_diff(current.splitlines(True), text.splitlines(True),
                                               f"{rel} (committed)", "generated"))
    print(f"{rel} is stale; run: python3 scripts/wdl-graph.py --write", file=sys.stderr)
    return 1


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--write", action="store_true", help=f"write {relpath(str(OUTPUT))}")
    ap.add_argument("--out", type=pathlib.Path, help="write the Markdown to this path instead")
    ap.add_argument("--check", action="store_true", help="exit 1 with a diff when the committed file is stale")
    ap.add_argument("--print", metavar="ENTRY", help="print the bare Mermaid source of one entrypoint")
    ap.add_argument("--depth", type=int, help=f"inline called workflows this deep (default {DEFAULT_DEPTH})")
    ap.add_argument("--hide", help=f"comma-separated call names to omit (default {','.join(sorted(HIDE))})")
    ap.add_argument("--max-chars", type=int, default=MAX_CHARS, help=f"size budget per diagram (default {MAX_CHARS})")
    a = ap.parse_args(argv)
    hide = frozenset(a.hide.split(",")) if a.hide is not None else HIDE
    try:
        if a.print:
            ep = a.print
            depth = a.depth if a.depth is not None else DEPTH.get(ep, DEFAULT_DEPTH)
            text, _ = graph_for(REPO / "workflows" / f"{ep}.wdl", depth, hide, a.max_chars)
            sys.stdout.write(text)
            return 0
        text = markdown(a.depth, hide, a.max_chars)
    except SizeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if a.check:
        return check(text, a.out or OUTPUT)
    if a.write or a.out:
        target = a.out or OUTPUT
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        print(f"wrote {relpath(str(target))}", file=sys.stderr)
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
